name: IMAGE PUSH TO ECR

on:
  workflow_dispatch:
  push:
    branches:
      - feature
    paths:
      - backend/**
      - .github/workflows/**

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1 # your AWS region
  ECR_REPOSITORY: dev/practice # your ECR repository name
  ECR_REGISTRY: 996109426400.dkr.ecr.ap-northeast-1.amazonaws.com # your ECR registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credential
        # if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_FOR_GOLANG }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:go-${{ github.sha }}
          registry: ${{ env.ECR_REGISTRY }}

