name: IMAGE PUSH TO ECR

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      # - .github/workflows/**

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1 # your AWS region
  ECR_REPOSITORY: dev/practice # your ECR repository name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credential
        # if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_FOR_GOLANG }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          registry: ${{ env.ECR_REGISTRY }}
          image: ${{ env.ECR_REPOSITORY }}
          tags: go-${{ github.run_number }}
          dockerfile: ./backend/Dockerfile
